import SideBar from '@/components/admin/SideBar'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Admin',
  description: 'Generated by Admin',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex px-[1vw] py-[1vh] w-screen h-screen overflow-hidden'>
        <SideBar/>
        {children}
        </body>
    </html>
  )
}
