import SideBar from "@/components/admin/SideBar";
import type { Metadata } from "next";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by Admin",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookie = cookies().get("_adm_");

  if (!cookie) {
    console.log(typeof window);
    console.log("cookie", cookie);
  }

  

  return (
      <div className="flex px-[1vw] py-[1vh] w-screen h-screen overflow-hidden">
     { !cookie ? (
          <div className="flex flex-col items-center justify-center w-full h-full">
            <h1 className="text-3xl font-bold">Login</h1>
          </div>
        ) :
         (
          <>
            <SideBar />
            {children}
          </>
        )}
      </div>
  );
}
