import Navbar from '@/components/NavBar'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Farrage',
  description: 'Generated by Qul 22',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        </body>
    </html>
  )
}
